# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "mjtsai1974&#39;s Dev Blob"
tagline:             'mjt&#39;s AI world'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://mjtsai1974.github.io/DevBlog/
baseurl:             '/DevBlog'
paginate:            5

# About/contact
author:
  name:              Mjtsai1974
  url:               https://www.facebook.com/mj.tsai.31
  email:             mjtsai1974@gmail.com

# Custom vars
version:             1.0.2
