# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "mjtsai1974&#39;s Dev Blob"
tagline:             'Welcome to mjt&#39;s AI world'
description:         'It&#39;s a place I keep record each of my review in the field of Artificial Intelligence.'
url:                 https://mjtsai1974.github.io/DevBlog/
baseurl:             '/DevBlog'
paginate:            5

# About/contact
author:
  name:              Mjtsai1974
  url:               https://www.facebook.com/mj.tsai.31
  email:             mjtsai1974@gmail.com

# Custom vars
version:             1.0.3
